biblioteca/apps/circulacion/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^panel/prestamo/$',
        views.LectorPrestamoView.as_view(),
        name="lectorPrestamo"
    ),
    url(
        r'^panel/prestamo/(?P<pk>\d+)/$',
        views.EjemplarPrestamoView.as_view(),
        name="ejemplarPrestamo"
    ),
    url(
        r'^panel/prestamo/confirmar/(?P<pk>\d+)/(?P<codigo>[\w-]+)/$',
        views.ConfirmarPrestamoView.as_view(),
        name="confirmarPrestamo"
    ),
    url(
        r'^panel/prestamo/registrar/(?P<pk>\d+)/(?P<codigo>[\w-]+)/$',
        views.RegistrarPrestamoView.as_view(),
        name="registarPrestamo"
    ),
    url(
        r'^panel/imprimir/voucher/prestamo/(?P<pk>\d+)/$',
        views.VoucherView.as_view(),
        name='printVoucher'
    ),
    url(
        r'^panel/devolucion/$',
        views.DevolverView.as_view(),
        name="devolver"
    ),
    url(
        r'^panel/devolucion/detalle/(?P<pk>\d+)/$',
        views.DetalleDevolucionView.as_view(),
        name="devolverDetalle"
    ),
    url(
        r'^deudores/$',
        views.ReporteDeudoresView.as_view(),
        name="reporteDeudores"
    ),
]

biblioteca/biblioteca/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.autores.urls', namespace="autor_app")),
    url(r'^', include('apps.catalogacion.urls', namespace="catalogacion_app")),
    url(r'^', include('apps.circulacion.urls', namespace="circulacion_app")),
    url(r'^', include('apps.lector.urls', namespace="lector_app")),
    url(r'^', include('apps.users.urls', namespace="users_app")),

    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    ]

biblioteca/apps/circulacion/models.py
from django.db import models
from django.conf import settings

from apps.herencia.models import TimeStampModel
from apps.lector.models import Lector, Biblioteca
from apps.catalogacion.models import Ejemplar


class Prestamo(TimeStampModel):
    bibliotecario = models.ForeignKey(settings.AUTH_USER_MODEL , editable=False)
    lector = models.ForeignKey(Lector)
    ejemplar = models.ForeignKey(Ejemplar)
    fecha_entrega = models.DateField()
    devuelto = models.BooleanField(default=False)
    #la ubicacion lo obtendremos de la ubicacion del ejemplar
    #biblioteca = models.ForeignKey(Biblioteca, blank=True, null=True)

    def __unicode__(self):
        return "%s %s" % (str(self.pk), self.lector)


class Devolucion(models.Model):
    prestamo = models.ForeignKey(Prestamo)
    bibliotecario = models.ForeignKey(settings.AUTH_USER_MODEL, editable=False)
    fecha_devolucion = models.DateField()

    class Meta:
        verbose_name_plural = 'Devoluciones'


class Semestre(models.Model):
    nombre = models.CharField(max_length=10) #ejemplo: 2016-1
    inicio_semestre = models.DateField()
    fin_semestre = models.DateField()

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.nombre)
        super(Semestre, self).save(*args, **kwargs)

biblioteca/apps/circulacion/forms.py
# -*- encoding: utf-8 -*-

from django import forms
from .models import Prestamo

from apps.lector.models import Lector,TipoLector,Biblioteca
from apps.catalogacion.models import Ejemplar

from datetime import date


class LectorPrestamoForm(forms.Form):
    lector = forms.CharField(
        label='número de carnet',
        widget=forms.TextInput(attrs={'class': 'validate'}),
    )

    def clean(self):
        cleaned_data = super(LectorPrestamoForm, self).clean()
        codigo = cleaned_data.get('lector')

        existe_lector = Lector.objects.filter(codigo=codigo).exists()
        if not existe_lector:
            mensaje = 'El lector no esta registrado'
            raise forms.ValidationError(mensaje)
        else:
            lector = Lector.objects.get(codigo=codigo)
            if not lector.fecha_inicio or not lector.fecha_fin:
                mensaje = 'El lector no se encuentra matriculado en el semestre'
                raise forms.ValidationError(mensaje)
            hoy = date.today();
            # verficamos el rango de fechas
            if not (lector.fecha_inicio < hoy and hoy < lector.fecha_fin):
                mensaje = 'El carnet del lector a caducado.'
                raise forms.ValidationError(mensaje)

        return cleaned_data


class LibroPrestamoForm(forms.Form):
    codigo = forms.CharField(
        label='codigo de barras',
        widget=forms.TextInput(
            attrs={'class': 'validate', 'placeholder': 'Ingrese codigo de barras'}
        ),
    )

    def clean(self):
        cleaned_data = super(LibroPrestamoForm, self).clean()
        codigo = cleaned_data.get('codigo')
        existe_codigo = Ejemplar.objects.filter(codigo_barras=codigo).exists()
        if not existe_codigo:
            mensaje = 'el item no esta registrado'
            raise forms.ValidationError(mensaje)
        else:
            ejemplar = Ejemplar.objects.get(codigo_barras=codigo)
            prestado = ejemplar.prestado
            print prestado
            if prestado:
                mensaje = "El item se encuentra prestado"
                raise forms.ValidationError(mensaje)
        return cleaned_data


class DevolucionForm(forms.Form):
    codigo = forms.CharField(
        label='codigo de barras',
        widget=forms.TextInput(
            attrs={'class': 'validate', 'placeholder': 'Ingrese codigo de barras'}
        ),
    )

    def clean(self):
        cleaned_data = super(DevolucionForm, self).clean()
        codigo = cleaned_data.get('codigo')
        prestamo = Prestamo.objects.filter(ejemplar__codigo_barras=codigo)
        if not prestamo.exists():
            print '1 error'
            mensaje = 'El ejemplar no existe'
            raise forms.ValidationError(mensaje)
        elif not prestamo[0].ejemplar.prestado:
            print '2 error'
            mensaje = 'El ejemplar no se encuentra prestado'
            raise forms.ValidationError(mensaje)
        return cleaned_data

class DeudoresForm(forms.Form):
    tipo_lector = forms.ModelChoiceField(empty_label="(Seleccione tipo de lector)",queryset=None)
    biblioteca = forms.ModelChoiceField(empty_label="(todos)",queryset=None,required=False)

    def __init__(self, *args, **kwargs):
        super(DeudoresForm,self).__init__(*args, **kwargs)
        self.fields['tipo_lector'].queryset = TipoLector.objects.all().order_by('nombre')
        self.fields['biblioteca'].queryset = Biblioteca.objects.all().order_by('nombre')

biblioteca/apps/circulacion/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView, View, RedirectView
from django.views.generic.edit import FormView, FormMixin
from django.views.generic.detail import DetailView, SingleObjectMixin

from django.core.urlresolvers import reverse_lazy

# local model import
from apps.lector.models import Lector,TipoLector,Biblioteca
from apps.circulacion.models import Ejemplar
from .models import Prestamo, Devolucion

# Local Import
from .functions import generar_pdf
from .forms import LectorPrestamoForm, LibroPrestamoForm, DevolucionForm,DeudoresForm
from datetime import date, datetime, timedelta

from django.db.models import Q
from django.shortcuts import render_to_response


class LectorPrestamoView(FormView):
    template_name = 'circulacion/prestamo/prestamo.html'
    print 'Sali a prestamo'
    form_class = LectorPrestamoForm
    # success_url = reverse_lazy('users_app:login')
    def get_success_url(self):
        return reverse_lazy('users_app:login')

    def form_valid(self, form):
        codigo = form.cleaned_data['lector']
        lector = Lector.objects.get(codigo=codigo)
        return redirect('circulacion_app:ejemplarPrestamo', pk=lector.pk)


class EjemplarPrestamoView(FormMixin, DetailView):
    '''
    Relizacion del prestamos si por dia
    '''
    model = Lector
    template_name = 'circulacion/prestamo/ejemplar.html'
    form_class = LibroPrestamoForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super(EjemplarPrestamoView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        # recuperamos el lector y verificamos los libros que tienen prestado
        lector = self.object
        context['prestamos'] = Prestamo.objects.filter(
            lector=lector,
            ejemplar__prestado=True,
            devuelto=False
        )
        context['cantidad'] = context['prestamos'].count()
        return  context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        bibliotecario = self.request.user
        lector = self.object

        # Cantidad de prestamos
        cantidad = Prestamo.objects.filter(lector=lector, devuelto=False).count()
        # recuperar codigo del libro
        codigo = form.cleaned_data["codigo"]

        if cantidad != 0:
            return redirect('circulacion_app:confirmarPrestamo', pk=lector.pk, codigo=codigo)
        else:
            # recuperarmos el ajemplar
            ejemplar = Ejemplar.objects.get(codigo_barras=codigo)
            # recuepramos la fecha de hoy
            hoy = datetime.now()
            dia = hoy.isoweekday()

            if dia == 5:
                # si es viernes se suma 3 dias al la fecha de entrega
                fecha_entrega = hoy + timedelta(days=3)
            else:
                # si el dia es distinto de viernes sol ose suma 1 dia
                fecha_entrega = hoy + timedelta(days=1)

            # Guardamos el prestamo
            prestamo = Prestamo(
                bibliotecario=bibliotecario,
                lector=lector,
                ejemplar=ejemplar,
                fecha_entrega=fecha_entrega
            )
            prestamo.save()

            # ponemos el libro como Prestado y guardamos
            ejemplar.prestado = True
            ejemplar.save()

            return redirect('circulacion_app:printVoucher', pk=prestamo.pk)



class ConfirmarPrestamoView(DetailView):
    '''
    Confirmar el prestamos si el lector tiene mas de dos prestamos
    '''
    model = Lector
    template_name = 'circulacion/prestamo/confirmacion.html'

    def get_context_data(self, **kwargs):
        context = super(ConfirmarPrestamoView, self).get_context_data(**kwargs)
        # recuperamos el lector y verificamos los libros que tienen prestado
        lector = self.object
        codigo_barras = self.kwargs.get("codigo")
        context['ejemplar'] = Ejemplar.objects.get(codigo_barras=codigo_barras)
        context['prestamos'] = Prestamo.objects.filter(
            lector=lector,
            ejemplar__prestado=True
        )
        context['cantidad'] = context['prestamos'].count()
        return  context


class RegistrarPrestamoView(View):

    def get(self, request, *args, **kwargs):
        print 'entre a redirectview'
        print self.args
        print self.kwargs
        bibliotecario = self.request.user
        lector = Lector.objects.get(pk=self.kwargs.get('pk'))
        print "lectorrrrr"
        print lector
        ejemplar = Ejemplar.objects.get(codigo_barras=self.kwargs.get('codigo'))

        hoy = datetime.now()
        dia = hoy.isoweekday()

        if dia == 5:
            # si es viernes se suma 3 dias al la fecha de entrega
            fecha_entrega = hoy + timedelta(days=3)
        else:
            # si el dia es distinto de viernes sol ose suma 1 dia
            fecha_entrega = hoy + timedelta(days=1)

        # Guardamos el prestamo
        prestamo = Prestamo(
            bibliotecario=bibliotecario,
            lector=lector,
            ejemplar=ejemplar,
            fecha_entrega=fecha_entrega,
        )
        print "vamo presmo"
        prestamo.save()

        # ponemos el libro como Prestado y guardamos
        ejemplar.prestado = True
        ejemplar.save()

        return redirect('circulacion_app:printVoucher', pk=prestamo.pk)

class VoucherView(SingleObjectMixin, View):
    model = Prestamo

    def get(self, request, *args, **kwargs):
        prestamo = self.get_object()
        return generar_pdf(
            'circulacion/prestamo/print_voucher.html',
            {'pagesize' : 'A4', 'prestamo' : prestamo}
        )

class DevolverView(FormView):
    form_class = DevolucionForm
    template_name = 'circulacion/devolucion/devolucion.html'
    success_url = reverse_lazy('circulacion_app:devolverDetalle')

    def form_valid(self, form):
        # recuperamos los datos del bibliotecario
        bibliotecario = self.request.user
        # recuperar codigo del libro
        codigo = form.cleaned_data["codigo"]
        # recuperamos la hora y fecha actual
        fecha_devolucion = date.today()
        # recuperamos el prestamo decuardo al codigo de barras
        prestamo = Prestamo.objects.get(ejemplar__codigo_barras=codigo, devuelto=False)
        # Cambiamos el estado del prestamo a falso y lo guardamos
        prestamo.ejemplar.prestado = False
        prestamo.ejemplar.save()
        prestamo.devuelto = True
        prestamo.save()
        devolucion = Devolucion(
            prestamo=prestamo,
            bibliotecario=bibliotecario,
            fecha_devolucion=fecha_devolucion,
        )
        devolucion.save()
        return redirect('circulacion_app:devolverDetalle', pk=prestamo.pk)


class DetalleDevolucionView(DetailView):
    model = Prestamo
    template_name = 'circulacion/devolucion/detalle_devolucion.html'


class ReporteDeudoresView(SingleObjectMixin, FormMixin, TemplateView):

    form_class = DeudoresForm

    def get(self, request, *args, **kwargs):
        usuario = self.request.user
        if request.method == 'GET':
            form2 = DeudoresForm(request.GET)
            if form2.is_valid():
                qset = Q()
                #Recuperar valores
                hoy = datetime.now()
                categoria = request.GET.get('tipo_lector','')
                biblioteca = request.GET.get('biblioteca','')
                qset.add(Q(devuelto=False), qset.AND)
                qset.add(Q(fecha_entrega__lte=hoy), qset.AND)
                if categoria:
                    categoria = TipoLector.objects.get(id=categoria)
                    qset.add(Q(lector__tipo=categoria), qset.AND)
                if biblioteca:
                    biblioteca = Biblioteca.objects.get(id=biblioteca)
                    qset.add(Q(ejemplar__ubicacion=biblioteca), qset.AND)
                
                results = Prestamo.objects.filter(qset).distinct().order_by('lector__apellidos_y_nombres')
                
                print results

                #datos para el pdf
                fecha = datetime.now() #fecha actual
                formatofecha = fecha.strftime("%d/%m/%Y") 
                return generar_pdf('reporte/reporte_deudores.html', {'pagesize':'A4', 'fecha': formatofecha, 'resultado': results, 'tipo': categoria})
            else: #formulario no valido
                form2 = DeudoresForm(request.GET)

        return render_to_response('reporte/form_deudores.html',{'form2': form2, 'user':usuario})

biblioteca/templates/circulacion/prestamo/confirmacion.html
{% extends "users/panel/panel.html" %}

{% block title %}Prestamo{% endblock title %}

  {% block titulo_nav %}  Prestamo {% endblock titulo_nav %}

{% block contenido_panel %}
    <div class="container">
        <div class="row">
            <h5 class="center-align title-prestamo">
                <span>El lector {{ lector|title }} tiene {{ cantidad }} item(s) para devolver </span>
            </h5>
        </div>
        <div class="row">
            <div class="col s12 m6 offset-m3">
                <div class="card-panel grey lighten-5 z-depth-1">
                    <div class="row valign-wrapper">
                        <form method="POST">{% csrf_token %}
                            <div class="col s12">
                                <h6 class="center-align">¿Desea prestar el item "{{ ejemplar.material.titulo|title }}" con codigo de barra "{{ ejemplar.codigo_barras }}"?</h6>
                            </div>
                            <div class="col s12 center">
                                <a href="{% url 'circulacion_app:registarPrestamo' lector.pk ejemplar.codigo_barras %}" class="waves-effect waves-light btn btn-panel blue">si</a>
                                <a href="{% url 'circulacion_app:lectorPrestamo' %}" class="waves-effect waves-light btn panel-btn white black-text">no</a>
                            </div>
                        </form>
                    </div>
                </div><!-- fin de card-panel -->

            </div>
        </div><!-- fin de row -->

    </div>
{% endblock contenido_panel %}

biblioteca/templates/circulacion/prestamo/ejemplar.html
{% extends "users/panel/panel.html" %}

{% load staticfiles %}

{% block title %}Prestamo{% endblock title %}

  {% block titulo_nav %}  Prestamo Libro {% endblock titulo_nav %}

{% block contenido_panel %}
    <div class="container">
        <div class="row">
            <div class="col s12 m4">
                <div class="card border-side top-margin">
                    <div class="card-content center">
                        <figure>
                            {% if not lector.avatar %}
                                <img class="responsive-img circle" src="{% static 'img/usuario.png' %}" alt="img">
                            {% else %}
                                <img class="responsive-img circle" src="{{ lector.avatar.url }}" alt="img">
                            {% endif %}
                        </figure>
                        <div class="lector">
                            <div>
                                <span class="lector-name">{{ lector.apellidos_y_nombres|title }}</span>
                            </div>
                            <div>
                                <span>{{ lector.carrera|title }}</span>
                            </div>
                            <div>
                                <span>{{ lector.codigo }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col s12 m8">
                <div class="card border-side top-margin">
                    <div class="card-content">
                        <div>
                            <span class="lector-name">Prestado a: {{ lector.apellidos_y_nombres|title }}</span>
                        </div>
                        <hr>
                        <div class="row">
                            <form method="post" class="col s12">{% csrf_token %}
                            <div class="row">
                                <div class="input-field col s6">
                                  {{ form.codigo }}
                                  {{ form.codigo.label_tag }}
                                </div>
                                <div class="input-field col s4">
                                    <button class="btn orange lighten-1 waves-effect waves-light" type="submit" name="action">Prestar
                                    </button>
                                </div>
                            </div>
                            {% if form.errors %}
                                <div class="text-errors">
                                    {{ form.non_field_errors }}
                                </div>
                            {% endif %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col s12">
                <div class="card border-side top-margin">
                    <div class="card-content">
                        <div>
                            <span class="lector-name">{{ cantidad }} - Prestamo(s)</span>
                        </div>
                        <hr>
                        <div class="row">
                            <table class="bordered striped">
                                <thead>
                                    <tr>
                                        <th>Fecha devolución</th>
                                        <th>Titulo</th>
                                        <th>Tipo</th>
                                        <th>Signatura</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for prestamo in prestamos %}
                                        <tr>
                                            <td>{{ prestamo.fecha_entrega }}</td>
                                            <td>{{ prestamo.ejemplar.material.titulo }}</td>
                                            <td>{{ prestamo.ejemplar.material.tipo_material }}</td>
                                            <td>{{ prestamo.ejemplar.signatura }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock contenido_panel %}

biblioteca/templates/circulacion/prestamo/prestamo.html
{% extends "users/panel/panel.html" %}

{% block title %}Prestamo{% endblock title %}

  {% block titulo_nav %}  Prestamo {% endblock titulo_nav %}

{% block contenido_panel %}
    <div class="container">
        <div class="row">
            <h5 class="center-align title-prestamo">
                <span>Ingrese número de carnet</span>
            </h5>
            <div class="card-panel">
                <div class="row">
                    <form method="post" class="col s12">{% csrf_token %}
                        <div class="row">
                            <div class="input-field col s8">
                                <i class="mdi-action-picture-in-picture prefix"></i>
                                {{ form.lector }}
                                {{ form.lector.label_tag }}
                            </div>
                            <div class="input-field col s2">
                                <button class="btn cyan waves-effect waves-light" type="submit">buscar
                                    <i class="mdi-action-search left"></i>
                                </button>
                            </div>

                        </div>
                        {% if form.errors %}
                            <div class="text-errors">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>

    </div>
{% endblock contenido_panel %}

biblioteca/templates/circulacion/prestamo/print_voucher.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <style >
        @page {
            size: {{ pagesize }};
            @frame header_frame{
                -pdf-frame-content: headerContent;
                /*left: 5pt;
                top: 20pt;
                height: 100pt;*/
                left: 2.5cm;
                top: 2cm;
                height: 100pt;
                }

            @frame content_frame {
                    left: 2.5cm; width: 400pt; top: 1.5cm; height: 700pt;
            }
        }
    </style>
</head>
<body>

<p style="font-size: 15px; font-family: Arial; text-align:center;">
    </br></br> .......................................................... </br>
    FIRMA
</p>
<strong style="font-size: 12px; font-family: Arial; text-align:center;">UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO</strong>
            <p>Lugar:                         {{ prestamo.ejemplar.ubicacion }}</p>
            <p>Bibliotecario:                 {{ prestamo.bibliotecario.get_full_name|title }}</p>
            <pre style="font-size: 12px; font-family: Arial; text-align:left;">
            <strong>DATOS USUARIO </strong>
            <strong> Usuario                           : </strong>{{ prestamo.lector }}
            <strong> Codigo                            : </strong>{{ prestamo.lector.codigo }}
            <strong> Carrera/Dependencia    : </strong>{{ prestamo.lector.carrera }}
            <strong> Fecha del Prestamo      : </strong>{{ prestamo.created }}
            </pre>



            <pre style="font-size: 12px; font-family: Arial; text-align:left;">
            <strong>DATOS BIBLIOGRAFICOS </strong>
            <strong> Titulo                               : </strong>{{ prestamo.ejemplar.material.titulo }}
            <strong> Autor                               : </strong>{% for autor in prestamo.ejemplar.material.autor.all %} {{ autor }} {% if not forloop.last %},{% else %}.{% endif %}{% endfor %}
            <strong> Codigo de libro               : </strong>{{ prestamo.ejemplar.signatura }}
            <strong> Codigo de barras            : </strong>{{ prestamo.ejemplar.codigo_barras }}
            <strong> Fecha de devolucion      : </strong>{{ prestamo.fecha_entrega }}
            </pre>



</body>
</html>