biblioteca/apps/catalogacion/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^$',
        views.Index.as_view(),
        name="Index"
    ),
    url(
        r'^conozcanos/$',
        views.NosotrosView.as_view(),
        name="nosotros"
    ),
    url(
        r'^directorio/$',
        views.DirectorioView.as_view(),
        name="directorio"
    ),
    url(
        r'^contactenos/$',
        views.ContactenosView.as_view(),
        name="contactenos"
    ),
    url(
        r'^material/(?P<pk>\d+)$',
        views.MaterialView.as_view(),
        name="material"
    ),
    url(
        r'^busqueda/$',
        views.BusquedaView.as_view(),
        name="busqueda"
    ),
    url(
        r'^detalle/ver_pdf/(?P<pk>\d+)/$', 
        views.LeerPDFDoc.as_view(), 
        name='ver_pdf'
    ),
    url(r'^reporte_autor/(?P<pk>\d+)/$', 
        views.VerReporteAutor.as_view(),
        name='verreporte'
    ),
    url(r'^revisar_registros_del_sistema/$', 
        views.RevisarRegistroView.as_view(),
        name='RevisarRegistro'
    ),
    url(
        r'^$',
        views.TiposDeMaterialView.as_view(),
        name="tipos"
    )
]

biblioteca/apps/users/urls.py
from django.conf.urls import url
from .views import LogIn, PanelView

urlpatterns = [
    # url(r'^$', Index.as_view(), name="Index"),
    url(
        r'^login/$',
        LogIn.as_view(),
        name="login"
    ),
    url(
        r'^salir/$',
        'apps.users.views.LogOut',
        name="logout"
    ),
    url(
        r'^panel/$',
        PanelView.as_view(),
        name="Panel"
    ),
]

biblioteca/biblioteca/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.autores.urls', namespace="autor_app")),
    url(r'^', include('apps.catalogacion.urls', namespace="catalogacion_app")),
    url(r'^', include('apps.circulacion.urls', namespace="circulacion_app")),
    url(r'^', include('apps.lector.urls', namespace="lector_app")),
    url(r'^', include('apps.users.urls', namespace="users_app")),

    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    ]

biblioteca/apps/catalogacion/forms.py
# -*- coding: utf-8 -*- 
from django import forms
from .models import TipoMaterial
from django.forms.widgets import Select
from django.utils.encoding import force_unicode
from django.utils.html import escape, conditional_escape


TIPO_CHOICES = (
	 ('Catalogo de Biblioteca', {'label':'Catálogo de Biblioteca', 'disabled selected':True}), 
	 ('titulo',"Titulo"),
	 ('autor',"Autor"),
	 ('signatura',"Signatura Topográfica"),
	)

class SelectWithDisabled(Select):
    """
    Subclass of Django's select widget that allows disabling options.
    To disable an option, pass a dict instead of a string for its label,
    of the form: {'label': 'option label', 'disabled': True}
    """
    def render_option(self, selected_choices, option_value, option_label):
        option_value = force_unicode(option_value)
        if (option_value in selected_choices):
            selected_html = u' selected="selected"'
        else:
            selected_html = ''
        disabled_html = ''
        if isinstance(option_label, dict):
            if dict.get(option_label, 'disabled selected'):
                disabled_html = u' disabled selected="disabled selected"'
            option_label = option_label['label']
        return u'<option value="%s"%s%s>%s</option>' % (
            escape(option_value), selected_html, disabled_html,
            conditional_escape(force_unicode(option_label)))

class BusquedaForm(forms.Form):
	categoria = forms.ModelChoiceField(empty_label="Seleccione una categoría",queryset=None)
	descripcion = forms.CharField(max_length=100,
		widget=(
				forms.widgets.TextInput(attrs={'placeholder': 'Introduzca la búsqueda'})
				)
	)
	tipo =forms.ChoiceField(choices=TIPO_CHOICES, widget=SelectWithDisabled())

	def __init__(self, *args, **kwargs):
		super(BusquedaForm,self).__init__(*args, **kwargs)
		self.fields['categoria'].queryset = TipoMaterial.objects.all()

class RevisarRegistroForm (forms.Form):
	categoria = forms.ModelChoiceField(empty_label="Seleccione una categoría", queryset=None,required=False)
	descripcion = forms.CharField(max_length=100, required=False,
		widget=(
				forms.widgets.TextInput(attrs={'placeholder': 'Introduzca la búsqueda'})
				)
	)
	Mostrar_desde = forms.DateField(
		widget=(
			forms.widgets.DateInput(format="%d/%m/%Y", attrs={'class':'datepicker', 'required':'True'})
			)
	)
	Mostrar_hasta = forms.DateField(
	widget=(
			forms.widgets.DateInput(format="%d/%m/%Y", attrs={'class':'datepicker'})
		)
	)
#	Mostrar_desde = forms.DateField(
#		widget=forms.DateInput(format="%d/%m/%Y" , attrs={'class':'datepicker' }),)
#
#	Mostrar_hasta = forms.DateField(
#		widget=forms.DateInput(format="%d/%m/%Y", attrs={'class':'datepicker'}),)
#


	def __init__(self, *args, **kwargs):
		super(RevisarRegistroForm,self).__init__(*args, **kwargs)
		self.fields['categoria'].queryset = TipoMaterial.objects.all()


	def clean(self):
		if (self.cleaned_data.get('Mostrar_desde') >
            self.cleaned_data.get('Mostrar_hasta')):
			raise forms.ValidationError(
                "La fecha de inicio debe ser menor a la fecha final."
            )

        	return self.cleaned_data

biblioteca/apps/catalogacion/views.py
# -*- coding: utf-8 -*- 
from django.views.generic.edit import FormMixin
from django.views.generic.detail import SingleObjectMixin
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from django.views.generic import TemplateView, DetailView, ListView, View, FormView
from .models import Material, Ejemplar, TipoMaterial
from apps.autores.models import Autor
from apps.circulacion.models import Prestamo

from django.db.models import Q
#from django.core.paginator import Paginator, InvalidPage, EmptyPage, PageNotAnInteger


#pure-pagination
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger, InvalidPage
#from pure_pagination.mixins import PaginationMixin

from .forms import BusquedaForm, RevisarRegistroForm

from django.template.loader import render_to_string

from django.template import RequestContext
import cStringIO as StringIO
import ho.pisa as pisa
from datetime import datetime, date, time

class Index(FormMixin, TemplateView):
    form_class = BusquedaForm
    model = Material
    template_name = "catalogacion/index.html"

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['materiales'] = Material.objects.all()[:4]
        context['form'] = self.get_form()
        return context

class NosotrosView(FormMixin, TemplateView):
    form_class = BusquedaForm
    template_name = "catalogacion/nosotros.html"

    def get_context_data(self, **kwargs):
        context = super(NosotrosView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

class DirectorioView(FormMixin, TemplateView):
    form_class = BusquedaForm
    template_name = "catalogacion/directorio.html"

    def get_context_data(self, **kwargs):
        context = super(DirectorioView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

class ContactenosView(FormMixin, TemplateView):
    form_class = BusquedaForm
    template_name = "catalogacion/contactenos.html"

    def get_context_data(self, **kwargs):
        context = super(ContactenosView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

class MaterialView(FormMixin, DetailView):
    form_class = BusquedaForm
    model = Material
    template_name = "catalogacion/material.html"

    def get(self, request, *args, **kwargs):
    	self.object = self.get_object()
    	return super(MaterialView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MaterialView, self).get_context_data(**kwargs)
        material = self.object
        context['ejemplares'] = Ejemplar.objects.ejemplar_material(material)
        context['existencia'] = context['ejemplares'].count
        context['prestamos'] = Prestamo.objects.all().order_by('-created')
        context['form'] = self.get_form()
        return context

class BusquedaView(FormMixin, ListView):
    form_class = BusquedaForm
    model = Material
    model = TipoMaterial
    model = Ejemplar

    def get_context_data(self, **kwargs):
        context = super(BusquedaView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def get(self, request, *args, **kwargs):
        #Recuperar valores
        if request.method=='GET':
            categoria = request.GET.get('categoria')
            if (categoria != ""):
                categoria =  TipoMaterial.objects.get(id=categoria)
            tipo = request.GET.get('tipo','')
            print "TIPO"
            print tipo
            query = request.GET.get('descripcion', '')

            if((categoria == "") and (tipo == "") and (query == "")):
                results = Material.objects.all()
            else:
                if((categoria != "") and (tipo == "") and (query == "")):
                    results = Material.objects.filter(Q(tipo_material = categoria)).distinct()
                else:
                    if((categoria != "") and (tipo == "") and (query != "")):
                        results = Material.objects.filter(Q(tipo_material = categoria) & (Q(titulo__unaccent__icontains = query)|Q(autor__slug__unaccent__icontains = query))).distinct()
                    else:
                        if ((categoria == "") and (tipo != "") and (query != "")):
                            if tipo == 'titulo':
                                results = Material.objects.filter(Q(titulo__unaccent__icontains = query)).distinct()
                            else:
                                if tipo == 'autor':
                                    results = Material.objects.filter(Q(autor__slug__unaccent__icontains = query)).distinct()
                                else:
                                    if tipo == 'signatura':
                                        print "ENTRO 1"
                                        tempresult = Ejemplar.objects.filter(Q(signatura__icontains= query)).values_list('material', flat=True).distinct()
                                        print "results temp"
                                        print tempresult                                        
                                        results = Material.objects.filter(id__in=tempresult)
                                        print "results"
                                        print results
                        else:
                            if ((categoria != "") and (tipo != "") and (query != "")):
                                if tipo == 'titulo':
                                    results = Material.objects.filter(Q(titulo__unaccent__icontains = query) &
                                                                            Q(tipo_material = categoria)
                                                                          ).distinct()
                                else:
                                    if tipo == 'autor':
                                        results = Material.objects.filter(Q(tipo_material = categoria ) & 
                                                              Q(autor__slug__unaccent__icontains = query) 
                                                             ).distinct()
                                    else:
                                        if tipo == 'signatura':
                                            tempresult = Ejemplar.objects.filter(Q(signatura__icontains= query)).values_list('material', flat=True).distinct()
                                            results = Material.objects.filter(id__in=tempresult)
                            else:
                                if ((categoria == "") and (tipo == "") and (query != "")) or ((categoria == "") and (tipo != "") and (query == "")):
                                    tempresult = Ejemplar.objects.filter(Q(signatura__icontains= query)).values_list('material', flat=True).distinct()
                                    results = Material.objects.filter(Q(titulo__unaccent__icontains = query)|Q(autor__slug__unaccent__icontains = query)|Q(id__in=tempresult)).distinct()
        total = results.count() #numero total de materiales encontrados
        parametros = request.GET.copy() 
        if parametros.has_key('page'):
            del parametros['page']
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        # Provide Paginator with the request object for complete querystring generation

        p = Paginator(results, 10) #numero de items por pagina

        queryset = p.page(page)

        context = {
                'materiales':queryset,
                'parametros':parametros,
                'form':self.get_form,
                'total':total
        }
        return render(request, 'catalogacion/busqueda.html', context)

#Materialdetail
class LeerPDFDoc(SingleObjectMixin, View):

    model = Material

    def get(self, request, *args, **kwargs):
        nombre = self.get_object().archivo
        archivo = 'media/'+ str(nombre)
        with open(archivo, 'r') as pdf:
            response = HttpResponse(pdf.read(), content_type='application/pdf')
            response['Content-Disposition'] = 'inline;filename=some_file.pdf'
            return response
        pdf.closed


class AutorView(SingleObjectMixin, TemplateView):
    template_name = 'catalogacion/detalle_autor.html.html'
    model = Autor

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(AutorView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AutorView, self).get_context_data(**kwargs)
        context['materiales'] = self.object.material_set.all().order_by('-created')[:3]
        return context

def generar_pdf(html):
    result = StringIO.StringIO()
    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("UTF-8")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf') #mimetype
    return HttpResponse('Error al generar el PDF: %s' % cgi.escape(html))

class TiposDeMaterialView(TemplateView):
    model = TipoMaterial
    template_name = "catalogacion/include/header.html"

    def get_context_data(self, **kwargs):
        context = super(TiposDeMaterialView, self).get_context_data(**kwargs)
        context['tiposmat'] = TipoMaterial.objects.all()
        return context


class VerReporteAutor(SingleObjectMixin, View):

    model = Autor

    def get(self, request, *args, **kwargs):
        fecha = datetime.now() #fecha actual
        formatofecha = fecha.strftime("%d/%m/%Y")
        autor = self.get_object()
        materiales = Material.objects.filter(Q(autor__apellidos_y_nombres__icontains=autor)).distinct()

biblioteca/templates/catalogacion/include/header.html
{% load staticfiles %}

<div class=" row white container-social">
  <div class="col s12 l3 offset-l6 center">
    <div class="top-social">
      <div class="social">
        <span><a href="https://www.facebook.com/Universidad-Nacional-de-San-Antonio-Abad-del-Cusco-P%C3%A1gina-Oficial-527956800577647/"><i class="fa fa-facebook"></i></a></span>
        <!-- <span><a href="#"><i class="fa fa-twitter"></i></a></span> -->
        <span><a href="http://correo.unsaac.edu.pe/"><i class="fa fa-google-plus"></i></a></span>
      </div>
    </div>
  </div>
  <div class="col s12 l3 center">
    <a href="{%url 'users_app:login' %}">iniciar sesión</a>
  </div>
</div>

<nav class="red darken-4">
  <div class="container">
    <div class="nav-wrapper">
      <a href="{%url 'catalogacion_app:Index' %}"  class="brand-logo">Biblioteca UNSAAC - Cusco</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse">
        <i class="mdi-navigation-menu"></i>
      </a>

      <ul class="right hide-on-med-and-down">

        <li><a href="{%url 'catalogacion_app:Index' %}">Inicio</a></li>
        <li>
          <ul style="background-color:#FFFFFF" id="nosotros" class="dropdown-content">
            <li><a style="color:#B71C1C;" href="{%url 'catalogacion_app:nosotros' %}">Conózcanos</a></li>
            <li><a style="color:#B71C1C;" href="{%url 'catalogacion_app:directorio' %}">Directorio</a></li>
          </ul>

          <a class="dropdown-button valign-wrapper" data-activates="nosotros">Nosotros<i class="mdi-navigation-arrow-drop-down"></i></a>
        </li>
        <li><a href="{%url 'catalogacion_app:contactenos' %}">Contactenos</a></li>
        <!--<li>
          <ul id="matricula-dropdown" class="dropdown-content">
          
            <li><a href="#">tesis</a></li>
            <li class="divider"></li>
            <li><a href="#">revistas</a></li>
            <li class="divider"></li>
            <li><a href="#">libros</a></li>
             <li><a href="#">{{ tiposmat }}</a></li>
          </ul>
          <a class="dropdown-button valign-wrapper" data-activates="matricula-dropdown">publicaciones<i class="mdi-navigation-arrow-drop-down"></i></a>
        </li>-->


      </ul>

      <ul class="side-nav" id="mobile-demo">
        <li><a href="{%url 'catalogacion_app:Index' %}">Inicio</a></li>
        <li><a href="{%url 'catalogacion_app:nosotros' %}">Nosotros</a></li>
        <li><a href="#">Contactenos</a></li>
        <li><a href="{%url 'users_app:login' %}">Iniciar Sesión</a></li>
      </ul>

    </div>
  </div>
</nav>

<div class="row">
   <form class="col s12" method="GET" enctype="multipart/form-data" id="form_datos" action="/busqueda/"> {% csrf_token %}
    <div class="row">

      <div class="col s12 m3">
        <label>Categoría (*)</label>
        {{form.categoria}}
      </div>
      <div class="col s12 m3">
        <label>Catálogo de Biblioteca (*)</label>
        {{form.tipo}}
      </div>
      <div class="col s12 search-wrapper m6">
        <!--<i class="mdi-action-search"></i>
        <input type="text" name="Search" class="search-input z-depth-2" placeholder="busqueda">-->
        <section class="webdesigntuts-workshop">
            {{ form.descripcion|escape }}
            <button type="submit" name="action">Buscar</button>
        </section>
      </div>
    </div>

  </form>
</div>

biblioteca/templates/catalogacion/include/slider.html
{% load staticfiles %}
<div class="slider">
  <ul class="slides">
    <li>
        <img src="{% static 'slider/slider_01.jpg' %}">
        <!-- <img src="http://lorempixel.com/580/250/nature/1"> -->
    </li>
    <li>
        <img src="{% static 'slider/slider_03.jpg' %}" >
         <!-- <img src="http://lorempixel.com/580/250/nature/2"> -->
    </li>
    <li>
        <img src="{% static 'slider/slider_01.jpg' %}">
         <!-- <img src="http://lorempixel.com/580/250/nature/3"> -->
    </li>
    <li>
        <img src="{% static 'slider/slider_04.jpg' %}">
         <!-- <img src="http://lorempixel.com/580/250/nature/4"> -->
    </li>
  </ul>
</div>