biblioteca/apps/catalogacion/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^$',
        views.Index.as_view(),
        name="Index"
    ),
    url(
        r'^conozcanos/$',
        views.NosotrosView.as_view(),
        name="nosotros"
    ),
    url(
        r'^directorio/$',
        views.DirectorioView.as_view(),
        name="directorio"
    ),
    url(
        r'^contactenos/$',
        views.ContactenosView.as_view(),
        name="contactenos"
    ),
    url(
        r'^material/(?P<pk>\d+)$',
        views.MaterialView.as_view(),
        name="material"
    ),
    url(
        r'^busqueda/$',
        views.BusquedaView.as_view(),
        name="busqueda"
    ),
    url(
        r'^detalle/ver_pdf/(?P<pk>\d+)/$', 
        views.LeerPDFDoc.as_view(), 
        name='ver_pdf'
    ),
    url(r'^reporte_autor/(?P<pk>\d+)/$', 
        views.VerReporteAutor.as_view(),
        name='verreporte'
    ),
    url(r'^revisar_registros_del_sistema/$', 
        views.RevisarRegistroView.as_view(),
        name='RevisarRegistro'
    ),
    url(
        r'^$',
        views.TiposDeMaterialView.as_view(),
        name="tipos"
    )
]

biblioteca/biblioteca/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.autores.urls', namespace="autor_app")),
    url(r'^', include('apps.catalogacion.urls', namespace="catalogacion_app")),
    url(r'^', include('apps.circulacion.urls', namespace="circulacion_app")),
    url(r'^', include('apps.lector.urls', namespace="lector_app")),
    url(r'^', include('apps.users.urls', namespace="users_app")),

    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    ]

biblioteca/apps/catalogacion/forms.py
# -*- coding: utf-8 -*- 
from django import forms
from .models import TipoMaterial
from django.forms.widgets import Select
from django.utils.encoding import force_unicode
from django.utils.html import escape, conditional_escape


TIPO_CHOICES = (
	 ('Catalogo de Biblioteca', {'label':'Catálogo de Biblioteca', 'disabled selected':True}), 
	 ('titulo',"Titulo"),
	 ('autor',"Autor"),
	 ('signatura',"Signatura Topográfica"),
	)

class SelectWithDisabled(Select):
    """
    Subclass of Django's select widget that allows disabling options.
    To disable an option, pass a dict instead of a string for its label,
    of the form: {'label': 'option label', 'disabled': True}
    """
    def render_option(self, selected_choices, option_value, option_label):
        option_value = force_unicode(option_value)
        if (option_value in selected_choices):
            selected_html = u' selected="selected"'
        else:
            selected_html = ''
        disabled_html = ''
        if isinstance(option_label, dict):
            if dict.get(option_label, 'disabled selected'):
                disabled_html = u' disabled selected="disabled selected"'
            option_label = option_label['label']
        return u'<option value="%s"%s%s>%s</option>' % (
            escape(option_value), selected_html, disabled_html,
            conditional_escape(force_unicode(option_label)))

class BusquedaForm(forms.Form):
	categoria = forms.ModelChoiceField(empty_label="Seleccione una categoría",queryset=None)
	descripcion = forms.CharField(max_length=100,
		widget=(
				forms.widgets.TextInput(attrs={'placeholder': 'Introduzca la búsqueda'})
				)
	)
	tipo =forms.ChoiceField(choices=TIPO_CHOICES, widget=SelectWithDisabled())

	def __init__(self, *args, **kwargs):
		super(BusquedaForm,self).__init__(*args, **kwargs)
		self.fields['categoria'].queryset = TipoMaterial.objects.all()

class RevisarRegistroForm (forms.Form):
	categoria = forms.ModelChoiceField(empty_label="Seleccione una categoría", queryset=None,required=False)
	descripcion = forms.CharField(max_length=100, required=False,
		widget=(
				forms.widgets.TextInput(attrs={'placeholder': 'Introduzca la búsqueda'})
				)
	)
	Mostrar_desde = forms.DateField(
		widget=(
			forms.widgets.DateInput(format="%d/%m/%Y", attrs={'class':'datepicker', 'required':'True'})
			)
	)
	Mostrar_hasta = forms.DateField(
	widget=(
			forms.widgets.DateInput(format="%d/%m/%Y", attrs={'class':'datepicker'})
		)
	)
#	Mostrar_desde = forms.DateField(
#		widget=forms.DateInput(format="%d/%m/%Y" , attrs={'class':'datepicker' }),)
#
#	Mostrar_hasta = forms.DateField(
#		widget=forms.DateInput(format="%d/%m/%Y", attrs={'class':'datepicker'}),)
#


	def __init__(self, *args, **kwargs):
		super(RevisarRegistroForm,self).__init__(*args, **kwargs)
		self.fields['categoria'].queryset = TipoMaterial.objects.all()


	def clean(self):
		if (self.cleaned_data.get('Mostrar_desde') >
            self.cleaned_data.get('Mostrar_hasta')):
			raise forms.ValidationError(
                "La fecha de inicio debe ser menor a la fecha final."
            )

        	return self.cleaned_data

biblioteca/apps/catalogacion/views.py
# -*- coding: utf-8 -*- 
from django.views.generic.edit import FormMixin
from django.views.generic.detail import SingleObjectMixin
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from django.views.generic import TemplateView, DetailView, ListView, View, FormView
from .models import Material, Ejemplar, TipoMaterial
from apps.autores.models import Autor
from apps.circulacion.models import Prestamo

from django.db.models import Q
#from django.core.paginator import Paginator, InvalidPage, EmptyPage, PageNotAnInteger


#pure-pagination
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger, InvalidPage
#from pure_pagination.mixins import PaginationMixin

from .forms import BusquedaForm, RevisarRegistroForm

from django.template.loader import render_to_string

from django.template import RequestContext
import cStringIO as StringIO
import ho.pisa as pisa
from datetime import datetime, date, time

class Index(FormMixin, TemplateView):
    form_class = BusquedaForm
    model = Material
    template_name = "catalogacion/index.html"

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['materiales'] = Material.objects.all()[:4]
        context['form'] = self.get_form()
        return context

class NosotrosView(FormMixin, TemplateView):
    form_class = BusquedaForm
    template_name = "catalogacion/nosotros.html"

    def get_context_data(self, **kwargs):
        context = super(NosotrosView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

class DirectorioView(FormMixin, TemplateView):
    form_class = BusquedaForm
    template_name = "catalogacion/directorio.html"

    def get_context_data(self, **kwargs):
        context = super(DirectorioView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

class ContactenosView(FormMixin, TemplateView):
    form_class = BusquedaForm
    template_name = "catalogacion/contactenos.html"

    def get_context_data(self, **kwargs):
        context = super(ContactenosView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

class MaterialView(FormMixin, DetailView):
    form_class = BusquedaForm
    model = Material
    template_name = "catalogacion/material.html"

    def get(self, request, *args, **kwargs):
    	self.object = self.get_object()
    	return super(MaterialView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MaterialView, self).get_context_data(**kwargs)
        material = self.object
        context['ejemplares'] = Ejemplar.objects.ejemplar_material(material)
        context['existencia'] = context['ejemplares'].count
        context['prestamos'] = Prestamo.objects.all().order_by('-created')
        context['form'] = self.get_form()
        return context

class BusquedaView(FormMixin, ListView):
    form_class = BusquedaForm
    model = Material
    model = TipoMaterial
    model = Ejemplar

    def get_context_data(self, **kwargs):
        context = super(BusquedaView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def get(self, request, *args, **kwargs):
        #Recuperar valores
        if request.method=='GET':
            categoria = request.GET.get('categoria')
            if (categoria != ""):
                categoria =  TipoMaterial.objects.get(id=categoria)
            tipo = request.GET.get('tipo','')
            print "TIPO"
            print tipo
            query = request.GET.get('descripcion', '')

            if((categoria == "") and (tipo == "") and (query == "")):
                results = Material.objects.all()
            else:
                if((categoria != "") and (tipo == "") and (query == "")):
                    results = Material.objects.filter(Q(tipo_material = categoria)).distinct()
                else:
                    if((categoria != "") and (tipo == "") and (query != "")):
                        results = Material.objects.filter(Q(tipo_material = categoria) & (Q(titulo__unaccent__icontains = query)|Q(autor__slug__unaccent__icontains = query))).distinct()
                    else:
                        if ((categoria == "") and (tipo != "") and (query != "")):
                            if tipo == 'titulo':
                                results = Material.objects.filter(Q(titulo__unaccent__icontains = query)).distinct()
                            else:
                                if tipo == 'autor':
                                    results = Material.objects.filter(Q(autor__slug__unaccent__icontains = query)).distinct()
                                else:
                                    if tipo == 'signatura':
                                        print "ENTRO 1"
                                        tempresult = Ejemplar.objects.filter(Q(signatura__icontains= query)).values_list('material', flat=True).distinct()
                                        print "results temp"
                                        print tempresult                                        
                                        results = Material.objects.filter(id__in=tempresult)
                                        print "results"
                                        print results
                        else:
                            if ((categoria != "") and (tipo != "") and (query != "")):
                                if tipo == 'titulo':
                                    results = Material.objects.filter(Q(titulo__unaccent__icontains = query) &
                                                                            Q(tipo_material = categoria)
                                                                          ).distinct()
                                else:
                                    if tipo == 'autor':
                                        results = Material.objects.filter(Q(tipo_material = categoria ) & 
                                                              Q(autor__slug__unaccent__icontains = query) 
                                                             ).distinct()
                                    else:
                                        if tipo == 'signatura':
                                            tempresult = Ejemplar.objects.filter(Q(signatura__icontains= query)).values_list('material', flat=True).distinct()
                                            results = Material.objects.filter(id__in=tempresult)
                            else:
                                if ((categoria == "") and (tipo == "") and (query != "")) or ((categoria == "") and (tipo != "") and (query == "")):
                                    tempresult = Ejemplar.objects.filter(Q(signatura__icontains= query)).values_list('material', flat=True).distinct()
                                    results = Material.objects.filter(Q(titulo__unaccent__icontains = query)|Q(autor__slug__unaccent__icontains = query)|Q(id__in=tempresult)).distinct()
        total = results.count() #numero total de materiales encontrados
        parametros = request.GET.copy() 
        if parametros.has_key('page'):
            del parametros['page']
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        # Provide Paginator with the request object for complete querystring generation

        p = Paginator(results, 10) #numero de items por pagina

        queryset = p.page(page)

        context = {
                'materiales':queryset,
                'parametros':parametros,
                'form':self.get_form,
                'total':total
        }
        return render(request, 'catalogacion/busqueda.html', context)

#Materialdetail
class LeerPDFDoc(SingleObjectMixin, View):

    model = Material

    def get(self, request, *args, **kwargs):
        nombre = self.get_object().archivo
        archivo = 'media/'+ str(nombre)
        with open(archivo, 'r') as pdf:
            response = HttpResponse(pdf.read(), content_type='application/pdf')
            response['Content-Disposition'] = 'inline;filename=some_file.pdf'
            return response
        pdf.closed


class AutorView(SingleObjectMixin, TemplateView):
    template_name = 'catalogacion/detalle_autor.html.html'
    model = Autor

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(AutorView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AutorView, self).get_context_data(**kwargs)
        context['materiales'] = self.object.material_set.all().order_by('-created')[:3]
        return context

def generar_pdf(html):
    result = StringIO.StringIO()
    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("UTF-8")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf') #mimetype
    return HttpResponse('Error al generar el PDF: %s' % cgi.escape(html))

class TiposDeMaterialView(TemplateView):
    model = TipoMaterial
    template_name = "catalogacion/include/header.html"

    def get_context_data(self, **kwargs):
        context = super(TiposDeMaterialView, self).get_context_data(**kwargs)
        context['tiposmat'] = TipoMaterial.objects.all()
        return context


class VerReporteAutor(SingleObjectMixin, View):

    model = Autor

    def get(self, request, *args, **kwargs):
        fecha = datetime.now() #fecha actual
        formatofecha = fecha.strftime("%d/%m/%Y")
        autor = self.get_object()
        materiales = Material.objects.filter(Q(autor__apellidos_y_nombres__icontains=autor)).distinct()

biblioteca/templates/catalogacion/base_catalogacion.html
{% extends "base.html" %}

{% load  staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>

{% endblock css %}

{% block js %}
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>
{% endblock js %}

biblioteca/templates/catalogacion/busqueda.html
{% extends "catalogacion/base_catalogacion.html" %}

{% load staticfiles %}

{% block title %}Bibloteca central y especializada unsaac{% endblock title %}

{% block content %}

    {% include "catalogacion/include/header.html" %}

    <div class="container">

        <div class="row">
            <div class="col s12">
                <div class="card border-side top-margin">
                    <div class="card-content">
                            <div>
                                <span class="lector-name">Se a encontrado {{ total }} resultado(s) en la búsqueda</span>
                            </div>
                        <hr>
                        {% for material in materiales.object_list %}
                            <article class="row detalle-item">
                                <div class="col s3">
                                {% if not material.portada %}
                                    <img  class="responsive-img" src="{% static 'img/img_libro.jpg' %}" alt="libro">
                                {% else %}
                                    <img src="{{ material.portada.url }}" alt="libro" class="responsive-img" >
                                {% endif %}
                                </div>
                                <div class="col s8">
                                    <dl class="dl-detalle">
                                        <dt>Titulo</dt>
                                        <dd>{{material.titulo}} {{material.titulo_secundario}}</dd>
                                        <dt>Autor</dt>
                                        <dd>{% for autor in material.autor.all %}
                                        <a href="{% url 'catalogacion_app:verreporte' autor.pk %}">{{ autor }} {% if not forloop.last %},{% else %}.{% endif %}</a>
                                        {% endfor %}
                                        </dd>
                                        {%if material.editorial != "" or material.anio != "" or material.edicion != "" %}
                                        <dt>Editor</dt>
                                        <dd>{{material.editorial}} {{material.anio}} 
                                        {% if  material.edicion %}
                                            {{material.edicion}} edición
                                        {% endif %}</dd>
                                        {% endif %}
                                        <dt>ISBN</dt>
                                        <dd>{{material.isbn}}</dd>

                                        <a href="{% url 'catalogacion_app:material' material.pk %}">Ver más... <i class="mdi-av-my-library-books"></i></a>
                                    </dl>
                                </div>
                            </article>
                        {% endfor %}

                        {% if total > 0 %}
                            {% load i18n %}
                            <ul class="pagination">
                                {% if materiales.has_previous %}
                                    <li class="waves-effect"><a href="?{{ materiales.previous_page_number.querystring}}{% if parametros.urlencode %}&{{ parametros.urlencode }}{% endif %}" class="prev"><i class="mdi-av-skip-previous"></i></a></li>
                                {% endif %}
                                {% for page in materiales.pages %}
                                    {% if page %}
                                        {% ifequal page materiales.number %}
                                            <li class="active"><span class="current page">{{ page }}</span></li>
                                        {% else %}
                                             <li><a href="?{{ page.querystring }} {% if parametros.urlencode %}&{{ parametros.urlencode }}{% endif %}" class="page">{{ page }}</a></li>
                                        {% endifequal %}
                                    {% else %}
                                        ...
                                    {% endif %}
                                {% endfor %}
                                {% if materiales.has_next %}
                                     <li class="waves-effect"><a href="?{{ materiales.next_page_number.querystring }} {% if parametros.urlencode %}&{{ parametros.urlencode }}{% endif %}" class="next"><i class="mdi-av-skip-next"></i></a></li>
                                {% endif %}
                            </ul>
                        {% endif %}
                        
                        {% if errors %}
                            {{ errors}}
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock content %}

biblioteca/templates/catalogacion/contactenos.html
{% extends "catalogacion/base_catalogacion.html" %}

{% load staticfiles %}

{% block title %}Bibloteca central y especializada unsaac{% endblock title %}

{% block content %}

    {% include "catalogacion/include/header.html" %}
    
    <div class="row">
      <div class="card">
        <div class="col s12 m12 l12">
                <div class="card"> <!-- inicio del card panel -->
                <br>
                    <h2 class="flow-text center-align" style="color:#B71C1C"> <b>CONTÁCTENOS</b></h2>
                    <div class="row">
                      <div class="col s12 m12 l12">
                        <div class="card-content">
                          <span class="card-title" style="color:#B71C1C"> Correo electrónico:</span>
                          <div class="light" align="justify">
                                    biblioteca.central@unsaac.edu.pe
                          </div>
                        </div>
                      </div>
                    </div>
                    <!--
                    <div class="row">
                      <div class="col s12 m12 l12">
                        <div class="card-content">
                          <span class="card-title" style="color:#B71C1C">Ubiquenos</span>
                             <div class="well">
                              <iframe width="100%" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3879.218165981039!2d-71.9608521!3d-13.5221988!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x916dd5fdf70d465d%3A0xcbddd8e36a2171d!2sUNSAAC+(Universidad+Nacional+de+San+Antonio+Abad+del+Cusco)!5e0!3m2!1ses-419!2spe!4v1471832896670">
                              </iframe>
                              </div>

                        </div>
                      </div>
                    </div>
                    -->
                  </div>
                  </div>
                  </div>
                  </div>


{% endblock content %}

biblioteca/templates/catalogacion/index.html
{% extends "catalogacion/base_catalogacion.html" %}

{% load staticfiles %}

{% block title %}Biblioteca central y especializada UNSAAC{% endblock title %}

{% block content %}

    {% include "catalogacion/include/header.html" %}
    {% include "catalogacion/include/slider.html" %}

    <section class="Releases">
        <div class="container">
            <h5 class="center-align light-blue-text text-accent-4 title-section">Publicaciones Recientes.</h5>
            <div class="row">
              {% for material in materiales %}
                <div class="col s12 m3">
                    <div class="card">
                        <div class="card-image waves-effect waves-block waves-light">
                          {% if not material.portada %}
                            <img  class="activator" src="{% static 'img/img_libro.jpg' %}" alt="libro">
                          {% else %}
                            <img class="activator" src="{{ material.portada.url }}" alt="libro" >
                          {% endif %}
                        </div>
                        <div class="card-content">
                          <span class="card-title activator grey-text text-darken-4">{{ material.titulo |slice:":16"  }} 
                          {% if material.titulo|length > 16 %}
                            ...
                          {% endif %}<i class="mdi-navigation-more-vert right"></i></span>
                          <p><a href="{% url 'catalogacion_app:material' material.pk %}">Ver más...</a></p>
                        </div>
                        <div class="card-reveal">
                          <span class="card-title grey-text text-darken-4">{{ material.titulo}}<i class="mdi-navigation-close right"></i></span>
                             {% for autor in material.autor.all %}
                              <p>
                                {{ autor }}{% if not forloop.last %},{% else %}.{% endif %}
                              </p>
                             {% endfor %}

                        </div>
                    </div>
                </div>

              {% endfor %}
            </div>
        </div>
    </section>

{% endblock content %}

biblioteca/templates/catalogacion/material.html
{% extends "catalogacion/base_catalogacion.html" %}

{% load staticfiles %}

{% block title %}Biblioteca central y especializada unsaac{% endblock title %}

{% block content %}

    {% include "catalogacion/include/header.html" %}
                <div class="material row">
                    <div class="col s12 m4 card-image waves-effect waves-block waves-light">
                        <!-- <a href="{%url 'catalogacion_app:ver_pdf' material.pk %}" >  -->
                        {% if not material.portada %}
                            <img  class="imagen-mat" src="{% static 'img/img_libro.jpg' %}" alt="libro">
                        {% else %}
                            <img class="imagen-mat" src="{{ material.portada.url }}" alt="libro" >
                        {% endif %}
                        <!-- </a> -->
                    </div>
                    <div class="col s12 m8">
                        <p >
                            <b>TÍTULO: </b>{{ material.titulo}} 
                        </p>

                        {%if  material.titulo_secundario  != "" %}
                        <p>
                            <b>TÍTULO SECUNDARIO:</b> {{ material.titulo_secundario }}
                        </p>
                        {% endif %}
                        
                        <p><b>AUTORES:</b> {% for autor in material.autor.all %}
                                        <a href="{% url 'catalogacion_app:verreporte' autor.pk %}">{{ autor }} {% if not forloop.last %},{% else %}.{% endif %}</a>
                                        {% endfor %}
                        </p>
                       
                       {% if not material.archivo %}
                       <p></p>
                        {% else %}
                        <p><b>PDF:</b>
                            <a href="{%url 'catalogacion_app:ver_pdf' material.pk %}" > Leer PDF</a>
                        </p>
                        {% endif %}

                        <p>
                            <b>Existencia:</b> {{ existencia }}
                        </p>
                        <table class="responsive-table bordered striped">
                            <tr>
                                <td><b>TIPO</b></td>
                                <td><b>UBICACIÓN</b></td>
                                <td><b>SIGNATURA TOPOGRÁFICA</b></td>
                                <td><b>ESTADO</b></td>
                                <td><b>NUMERO DE COPIA</b></td>
                                <td><b>FECHA DE VENCIMIENTO</b></td>
                            </tr>
                            {% for ejemplar in  ejemplares %}
                            <tr>
                                <td>
                                    {{ material.tipo_material }}
                                </td>
                                <td>
                                {{ ejemplar.ubicacion}}
                                </td>
                                <td>
                                    {{ ejemplar.signatura }}
                                </td>
                                <td>
                                    {% if ejemplar.prestado %}
                                        Prestado
                                    {%else%}
                                        Disponible
                                    {% endif %}
                                </td>
                                <td>
                                    {{ ejemplar.numero_copia}}
                                </td>
                                <td>
                                {% if ejemplar.prestado %}
                                    {% for prestamo in prestamos  %}
                                        {% if ejemplar.codigo_barras == prestamo.ejemplar.codigo_barras and prestamo.devuelto == False %}
                                            {{prestamo.fecha_entrega}}
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                                </td>

                            </tr>
                            {% endfor %}
                        </table>
                    </div>

                </div>


{% endblock content %}