biblioteca/apps/catalogacion/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^$',
        views.Index.as_view(),
        name="Index"
    ),
    url(
        r'^conozcanos/$',
        views.NosotrosView.as_view(),
        name="nosotros"
    ),
    url(
        r'^directorio/$',
        views.DirectorioView.as_view(),
        name="directorio"
    ),
    url(
        r'^contactenos/$',
        views.ContactenosView.as_view(),
        name="contactenos"
    ),
    url(
        r'^material/(?P<pk>\d+)$',
        views.MaterialView.as_view(),
        name="material"
    ),
    url(
        r'^busqueda/$',
        views.BusquedaView.as_view(),
        name="busqueda"
    ),
    url(
        r'^detalle/ver_pdf/(?P<pk>\d+)/$', 
        views.LeerPDFDoc.as_view(), 
        name='ver_pdf'
    ),
    url(r'^reporte_autor/(?P<pk>\d+)/$', 
        views.VerReporteAutor.as_view(),
        name='verreporte'
    ),
    url(r'^revisar_registros_del_sistema/$', 
        views.RevisarRegistroView.as_view(),
        name='RevisarRegistro'
    ),
    url(
        r'^$',
        views.TiposDeMaterialView.as_view(),
        name="tipos"
    )
]

biblioteca/apps/circulacion/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^panel/prestamo/$',
        views.LectorPrestamoView.as_view(),
        name="lectorPrestamo"
    ),
    url(
        r'^panel/prestamo/(?P<pk>\d+)/$',
        views.EjemplarPrestamoView.as_view(),
        name="ejemplarPrestamo"
    ),
    url(
        r'^panel/prestamo/confirmar/(?P<pk>\d+)/(?P<codigo>[\w-]+)/$',
        views.ConfirmarPrestamoView.as_view(),
        name="confirmarPrestamo"
    ),
    url(
        r'^panel/prestamo/registrar/(?P<pk>\d+)/(?P<codigo>[\w-]+)/$',
        views.RegistrarPrestamoView.as_view(),
        name="registarPrestamo"
    ),
    url(
        r'^panel/imprimir/voucher/prestamo/(?P<pk>\d+)/$',
        views.VoucherView.as_view(),
        name='printVoucher'
    ),
    url(
        r'^panel/devolucion/$',
        views.DevolverView.as_view(),
        name="devolver"
    ),
    url(
        r'^panel/devolucion/detalle/(?P<pk>\d+)/$',
        views.DetalleDevolucionView.as_view(),
        name="devolverDetalle"
    ),
    url(
        r'^deudores/$',
        views.ReporteDeudoresView.as_view(),
        name="reporteDeudores"
    ),
]

biblioteca/apps/users/urls.py
from django.conf.urls import url
from .views import LogIn, PanelView

urlpatterns = [
    # url(r'^$', Index.as_view(), name="Index"),
    url(
        r'^login/$',
        LogIn.as_view(),
        name="login"
    ),
    url(
        r'^salir/$',
        'apps.users.views.LogOut',
        name="logout"
    ),
    url(
        r'^panel/$',
        PanelView.as_view(),
        name="Panel"
    ),
]

biblioteca/biblioteca/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.autores.urls', namespace="autor_app")),
    url(r'^', include('apps.catalogacion.urls', namespace="catalogacion_app")),
    url(r'^', include('apps.circulacion.urls', namespace="circulacion_app")),
    url(r'^', include('apps.lector.urls', namespace="lector_app")),
    url(r'^', include('apps.users.urls', namespace="users_app")),

    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    ]

biblioteca/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


class UserManager(BaseUserManager, models.Manager):

    def _create_user(self, username, email, password, is_staff, is_superuser, **extra_fields):

        if not email:
            raise ValueError("el email es obligatorio")
            
        email = self.normalize_email(email) 
        user = self.model(
            username=username,
            email=email,
            is_active=True,
            is_staff=is_staff,
            is_superuser=is_superuser,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, password=None, **extra_fields):
        return self._create_user(
            username, email, password, False, False, **extra_fields
        )

    def create_superuser(self, username, email, password, **extra_fields):
        return self._create_user(
            username, email, password, True, True, **extra_fields
        )


class User(AbstractBaseUser, PermissionsMixin):

    GENDER_CHOICES = (
        ('M', 'MASCULINO'),
        ('F', 'FEMENINO'),
    )
    username = models.CharField('username', max_length=30, unique=True)
    email = models.EmailField('correo electronico', unique=True)
    first_name = models.CharField('nombres', max_length=50)
    last_name = models.CharField('apellidos', max_length=50)
    avatar = models.ImageField(upload_to='users',blank=True, null=True )
    address = models.CharField('direccion', max_length=50)
    phone = models.CharField('telefono', max_length=50)
    gender = models.CharField('sexo', max_length=1, choices=GENDER_CHOICES)

    objects = UserManager()

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return "%s %s" % (self.first_name, self. last_name)

biblioteca/apps/users/forms.py
# -*- encoding: utf-8 -*-
from django import forms

from django.contrib.auth import authenticate
from .models import User


class LoginForm(forms.Form):
    username = forms.CharField(
        label='usuario',
        max_length='30',
        widget=forms.TextInput(attrs={'class': 'validate'}),
    )
    password = forms.CharField(
        label='contraseña',
        widget=forms.PasswordInput(attrs={'class': 'validate'}),
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if not authenticate(username=username, password=password):
            raise forms.ValidationError('usuario o contraseña incorrecta ..!!')
        return self.cleaned_data

biblioteca/apps/users/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.contrib.auth import authenticate, login, logout

from django.core.urlresolvers import reverse_lazy

from .forms import LoginForm
from django.db.models import Q
from apps.users.models import User
from django.http import HttpResponseRedirect
#from django.contrib.auth.models import Group


class LogIn(FormView):
    form_class = LoginForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('users_app:Panel')

    def form_valid(self, form):
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password']
        )
        if user is not None:
            if user.is_active:
                login(self.request, user)
                #recuperamos el nombre del usuario
                nombreuser = user.username
                print "username"
                print nombreuser
                consulta = User.objects.filter(Q(username=nombreuser)&Q(groups__name='catalogador'))
                if consulta:
                    #si el usuario pertence al grupo catalogador
                    return redirect('/admin')
                consulta = User.objects.filter(Q(username=nombreuser)&Q(groups__name='bibliotecario'))
                if consulta:
                    #si el usuario pertence al grupo bibliotecario
                    return super(LogIn, self).form_valid(form)     

        return super(LogIn, self).form_valid(form)
        
    
def LogOut(request):
    logout(request)
    return redirect('/')


class Index(TemplateView):
    template_name = 'users/index.html'


class PanelView(TemplateView):
    template_name = 'users/panel/panel.html'

biblioteca/templates/users/panel/base_panel.html
{% extends "base.html" %}

{% load  staticfiles%}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <link rel="stylesheet" href="{% static 'css/stylepanel.css' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>
{% endblock css %}

{% block sidenav %}
    <header>
        <nav class="top-nav red darken-4">
            <div class="container">
              <div class="nav-wrapper">
                <a href=""></a>
                <a class="page-title">{% block titulo_nav %}{% endblock titulo_nav %}</a>
              </div>
            </div>
        </nav>
        <div class="container">
            <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full">
              <i class="mdi-navigation-menu"></i>
            </a>
        </div>
        <ul id="nav-mobile" class="side-nav fixed">
            <li class="logo red darken-4">
              <div id="logo-container">
                <div class="row">
                  <div class="col col-profile s4">
                    {% if not user.avatar %}
                      <img src="{% static 'img/usuario.png' %}" alt="{{ user.get_full_name }}" class="circle responsive-img valign">
                    {% else %}
                        <img src="{{ user.avatar.url }}" alt="{{ user.get_full_name }}" class="circle responsive-img valign">
                    {% endif %}
                  </div>
                  <div class="col col-profile s8">
                    <ul id="profile-dropdown" class="dropdown-content">
                      <!-- <li><a href="#"><i class="mdi-action-face-unlock"></i> Perfil</a>
                      </li> -->
                      <li class="divider"></li>
                      <li><a href="{%url 'users_app:logout' %}"><i class="mdi-hardware-keyboard-tab"></i> Salir</a>
                      </li>
                    </ul>
                    <a class="waves-effect waves-light btn-flat white-text dropdown-button profile-btn" data-activates="profile-dropdown">{{ user.first_name }}<i class="mdi-navigation-arrow-drop-down right-profile"></i></a>
                    <p class="user-roal">Bienvenido {{user.username|capfirst}}</p>
                  </div>
                </div>
              </div>
            </li>

            {% block funciones %}{% endblock funciones %}

        </ul>
    </header>
    <main>
        {% block mensaje %}{% endblock mensaje %}
        {% block contenido_panel %}{% endblock contenido_panel %}

    </main>

{% endblock sidenav %}

{% block js %}
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>
{% endblock js %}

biblioteca/templates/users/panel/panel.html
{% extends "users/panel/base_panel.html" %}

{% block title %}panel{% endblock title %}

  {% block titulo_nav %} Panel de Administrador{% endblock titulo_nav %}

    {% block funciones %}
    <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
            {% if user.is_superuser %}
            <li class="bold"><a class="collapsible-header  waves-effect waves-teal">Administrador</a>
                <div class="collapsible-body">
                    <ul>
                        <li><a href="/admin">Ir al administrador</a></li>
                    </ul>
                </div>
            </li>
            {% endif %}

            <li class="bold"><a class="collapsible-header  waves-effect waves-teal">Circulación</a>
                <div class="collapsible-body">
                    <ul>
                        <li><a href="{% url 'circulacion_app:lectorPrestamo' %}">Prestamo</a></li>
                        <li><a href="{% url 'circulacion_app:devolver' %}">Devolución</a></li>
                    </ul>
                </div>
            </li>

            {% if user.is_superuser %}
            <li class="bold"><a class="collapsible-header waves-effect waves-teal"> Realizar Consultas</a>
              <div class="collapsible-body">
                    <ul>
                        <li><a href="{%url 'catalogacion_app:RevisarRegistro' %}">Reporte</a></li>
                        <li><a href="{%url 'circulacion_app:reporteDeudores' %}">Deudores</a></li>
                    </ul>
              </div>
            </li>
            {% endif %}

        </ul>
    </li>
    {% endblock funciones %}